name: deel
description: "A new Flutter project."

version: 1.0.14+34

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

#  camera_avfoundation: ^0.9.21+1
  image_picker: ^1.2.0
#  hl_image_picker: ^1.2.16
  path_provider: ^2.1.4
  package_info_plus: ^8.0.2
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.3.5
  firebase_messaging: ^15.2.10
  otp_text_field: ^1.1.3
  otp_pin_field:
    git:
      url: https://github.com/KiroAlbear/otp_pin_field_package.git
      ref: e0db767

  country_codes: ^3.1.0+2
  permission_handler: ^11.3.1
  flutter_screenutil: ^5.9.1
  image_loader:
    git:
      url: https://github.com/KiroAlbear/image_loader.git
      ref: ce970cd

  provider: ^6.1.2
  google_fonts: 6.2.1
  rxdart: ^0.27.7
  form_field_validator: ^1.1.0
  retrofit: ^4.6.0
  logger: any
  json_annotation: ^4.9.0
  custom_progress_button: ^2.0.1
  flutter_spinkit: ^5.2.1
  simple_shared_pref: ^2.0.6
  transition_easy: ^1.0.8
  flutterlifecyclehooks: ^4.0.0
  jwt_decoder: ^2.0.1
  http_parser: ^4.0.2
  location: ^7.0.1
  connectivity_plus: ^6.1.1
  intl: ^0.19.0
  device_info_plus: ^10.1.0
  local_auth: ^2.2.0
  url_launcher: ^6.3.0
  #  open_street_map_search_and_pick: ^0.1.1
  open_street_map_search_and_pick:
    git:
      url: https://github.com/KiroAlbear/open_street_map_search_and_pick.git
      ref: fb15ca7
  flutter_map: ^7.0.2
  lazy_load_scrollview: ^1.3.0
  easy_url_launcher: ^0.0.7
  flutter_zxing: ^2.2.1
  http: ^1.5.0
  index_generator: ^3.4.1
  mockito: ^5.4.4
  retrofit_generator: ^9.7.0
  timelines:
    git:
      url: https://github.com/KiroAlbear/timelines_pubdev.git
      ref: d58cdc41dcef4aaf093ad050eb3824d3ee8376aa
  geolocator: ^13.0.2
  http_mock_adapter: ^0.6.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dio_smart_retry: ^6.0.0
#  chucker_flutter: ^1.8.2
  dio_http2_adapter: ^2.6.0
  carousel_slider: ^5.0.0
  get_it: ^7.6.4
  go_router: ^12.1.3
  curved_labeled_navigation_bar: ^2.0.5
  flutter_paymob: ^1.0.4
  smooth_page_indicator: ^1.2.1
  otp_autofill: ^4.1.0
  shorebird_code_push: ^2.0.5
  flutter_phoenix: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.3
  build_runner: ^2.4.15
  json_serializable: ^6.8.0
  flutter_gen_runner:

dependency_overrides:

  intl: 0.18.1
  geolocator: ^10.1.0
  dart_style: ^3.1.1


index_generator:
  exclude:
    - 'main_app_live.dart'
    - 'main_app_stage.dart'
    - 'main_app_test.dart'
    - 'navigation_routes.dart'
    - 'core/dto/network/api_client_key.dart'
    - 'core/dto/network/admin_client_key.dart'
    - 'core/dto/network/dio_builder/dio_client.dart'
    - 'core/generated/*'
    - '**.g.dart'

  libraries:
    - directory_path: lib

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/svg/
    - assets/png/
  fonts:
    - family: DINNext
      fonts:
        - asset: assets/fonts/DINNext-Regular.ttf
        - asset: assets/fonts/DINNext-Medium.ttf
        - asset: assets/fonts/DINNext-Bold.ttf


flutter_flavorizr:
  flavorizr: flavorizr.yaml